# Generated by Django 4.2.30 on 2026-09-29 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Day number')),
                ('date', models.DateField(help_text='Date')),
                ('title', models.CharField(blank=True, default='', help_text='Day title', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Trip title', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(help_text='End date')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', help_text='Status', max_length=20)),
                ('budget_estimate', models.DecimalField(decimal_places=2, default=0, help_text='Budget estimate', max_digits=12)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image', null=True, upload_to='itineraries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('collaborator', 'Collaborator'), ('viewer', 'Viewer')], default='viewer', help_text='Role', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(help_text='Itinerary', on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='itineraries.itinerary')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='trip_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='companions',
            field=models.ManyToManyField(blank=True, help_text='Companions', related_name='shared_itineraries', through='itineraries.TripCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='owner',
            field=models.ForeignKey(help_text='Owner', on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DayActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order')),
                ('activity', models.ForeignKey(help_text='Activity', on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='bookings.activity')),
                ('daily_plan', models.ForeignKey(help_text='Daily plan', on_delete=django.db.models.deletion.CASCADE, related_name='day_activities', to='itineraries.dailyplan')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='itinerary',
            field=models.ForeignKey(help_text='Itinerary', on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='itineraries.itinerary'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(help_text='Itinerary', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='itineraries.itinerary')),
                ('user', models.ForeignKey(help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tripcollaborator',
            index=models.Index(fields=['user', 'role'], name='idx_collab_user_role'),
        ),
        migrations.AlterUniqueTogether(
            name='tripcollaborator',
            unique_together={('itinerary', 'user')},
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['owner'], name='idx_itin_owner'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['status'], name='idx_itin_status'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['start_date'], name='idx_itin_start'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('itinerary', 'day_number')},
        ),
    ]
