# Generated by Django 4.2.30 on 2026-09-29 12:04

from django.db import migrations, models
import django.db.models.deletion
import travel_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment'), ('hostel', 'Hostel'), ('villa', 'Villa'), ('resort', 'Resort'), ('guesthouse', 'Guest House')], help_text='Type', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price/night', max_digits=10)),
                ('address', models.TextField(blank=True, default='')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='Amenities list')),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/', validators=[travel_api.validators.validate_image_file])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(help_text='Check-in')),
                ('check_out', models.DateField(help_text='Check-out')),
                ('guests_count', models.PositiveIntegerField(default=1, help_text='Guests')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('activity_type', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('food', 'Food & Drink'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('transport', 'Transport')], help_text='Type', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price/person', max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration (min)')),
                ('description', models.TextField(blank=True, default='')),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', validators=[travel_api.validators.validate_image_file])),
                ('is_available', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date')),
                ('participants_count', models.PositiveIntegerField(default=1, help_text='Participants')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(help_text='Activity', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.activity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
