# Generated by Django 4.2.30 on 2026-09-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('itineraries', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='itinerary',
            field=models.ForeignKey(help_text='Itinerary', on_delete=django.db.models.deletion.CASCADE, related_name='activity_bookings', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(help_text='Destination', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='accommodation',
            field=models.ForeignKey(help_text='Accommodation', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='itinerary',
            field=models.ForeignKey(help_text='Itinerary', on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_bookings', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(help_text='Destination', on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.destination'),
        ),
        migrations.AddIndex(
            model_name='activitybooking',
            index=models.Index(fields=['itinerary'], name='idx_actbooking_itin'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['destination'], name='idx_activity_dest'),
        ),
        migrations.AddIndex(
            model_name='accommodationbooking',
            index=models.Index(fields=['itinerary'], name='idx_accombooking_itin'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['destination'], name='idx_accom_dest'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['price_per_night'], name='idx_accom_price'),
        ),
    ]
