# Generated by Django 4.2.30 on 2026-09-29 11:50

from django.db import migrations, models
import django.db.models.deletion
import travel_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL slug', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[travel_api.validators.validate_image_file])),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Destination name', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug', max_length=200, unique=True)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', validators=[travel_api.validators.validate_image_file, travel_api.validators.validate_file_size])),
                ('is_featured', models.BooleanField(default=False, help_text='Featured')),
                ('avg_rating', models.FloatField(default=0.0, help_text='Cached average rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='destinations.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL slug', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/photos/', validators=[travel_api.validators.validate_image_file, travel_api.validators.validate_file_size])),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(help_text='Destination', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='destinations.destination')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags', related_name='destinations', to='destinations.tag'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['country'], name='idx_dest_country'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['city'], name='idx_dest_city'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_featured'], name='idx_dest_featured'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['avg_rating'], name='idx_dest_rating'),
        ),
    ]
