# Generated by Django 6.1.1 on 2026-09-18 10:16

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Destination display name.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier.', max_length=220, unique=True)),
                ('country', models.CharField(help_text='Country this destination is in.', max_length=100)),
                ('description', models.TextField(help_text='Long-form description shown on the detail page.')),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation')], help_text='Primary destination category.', max_length=20)),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('dry', 'Dry'), ('temperate', 'Temperate'), ('continental', 'Continental'), ('polar', 'Polar')], help_text='Dominant climate type.', max_length=20)),
                ('best_time_to_visit', models.CharField(blank=True, help_text='E.g. "April - June".', max_length=200)),
                ('avg_daily_cost', models.DecimalField(decimal_places=2, help_text='Average daily cost in USD, used for budget filtering.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', validators=[accounts.validators.validate_image_file_size, accounts.validators.validate_image_extension])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive destinations are hidden from search.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'category'], name='destination_country_c7c612_idx'), models.Index(fields=['climate'], name='destination_climate_5ffe0c_idx'), models.Index(fields=['avg_daily_cost'], name='destination_avg_dai_7024ce_idx')],
            },
        ),
    ]
